name: black-action
on: [push, pull_request]
jobs:
  linter_name:
    name: runner & black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          black_args: ". --check"
          src: "."
